<?php

use App\Http\Controllers\ArticleController;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    $articles = [
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc id sollicitudin libero. Phasellus porttitor neque at erat malesuada fringilla. Nam varius eleifend lectus vel efficitur. Quisque in libero sit amet massa finibus egestas a a justo. Sed feugiat sodales dui, non eleifend massa convallis a. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent id varius felis. Praesent ac volutpat lacus. Nam tempus aliquam urna non auctor. Pellentesque at viverra arcu, eget faucibus dui. Suspendisse vel aliquet magna. Duis faucibus eu nunc nec interdum. Fusce id ante vel mi vehicula viverra. Duis sagittis cursus auctor. Nunc euismod neque non dignissim faucibus. Sed feugiat molestie nisl, hendrerit sodales libero rhoncus non. In hac habitasse platea dictumst. Nunc iaculis, augue ut semper elementum, turpis nisl aliquet sapien, sit amet fermentum velit risus sit amet lacus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Integer venenatis et leo et commodo. Duis malesuada tortor in dui tempus aliquet non eget urna. Curabitur quam nisi, fermentum non condimentum eu, ultricies vitae sem. Integer eget erat non nisl feugiat interdum. Aenean quis nisi at leo congue pharetra et vel nunc. Cras ullamcorper auctor diam, ut posuere tortor malesuada ut.',
        'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Ut vehicula imperdiet consequat. Sed efficitur mollis pretium. Curabitur eu vulputate eros, ac porta quam. In hac habitasse platea dictumst. Morbi porta molestie augue at luctus. Phasellus quis libero dui. Vestibulum urna tortor, accumsan in tempus eget, vehicula vitae diam. Cras id accumsan dui. Donec fringilla posuere commodo. Praesent feugiat tellus augue, in sollicitudin arcu mattis quis. Maecenas rutrum luctus massa faucibus suscipit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi a lorem eros. Nam a orci sed dolor cursus fringilla.',
        'Maecenas nec tincidunt sapien, eu ullamcorper magna. Cras faucibus lacus sed tempor pretium. Curabitur vitae vehicula turpis. In condimentum accumsan lacus, non bibendum mi imperdiet non. Vestibulum turpis lectus, gravida nec auctor vel, commodo at risus. Quisque iaculis turpis a sapien luctus dignissim. Nunc feugiat congue imperdiet. Morbi gravida vitae enim semper faucibus. Nulla luctus enim vitae dapibus luctus. Nulla mollis malesuada turpis vitae sodales. Phasellus augue erat, commodo et quam vitae, pulvinar maximus nunc. Duis sed tempus dui, eget scelerisque purus. Praesent eu elit sit amet ante vestibulum consequat et at lacus. Mauris pulvinar vitae turpis et mattis. Quisque accumsan tellus tortor, a finibus felis aliquam vitae. Donec congue tellus elementum eros maximus, eget tincidunt ex luctus. Maecenas sit amet erat eu lorem vehicula faucibus. Nullam fringilla magna quis viverra vestibulum. Phasellus est massa, ultrices non volutpat sit amet, bibendum at odio. Mauris porta congue quam sit amet pellentesque. In mollis tellus pellentesque ultrices efficitur. Maecenas bibendum mattis finibus. Curabitur et facilisis augue. Nunc consequat condimentum efficitur. Nunc bibendum metus eu lacus cursus volutpat. Etiam sed nunc eget felis elementum posuere quis ut tortor. Vivamus volutpat porttitor dolor, vitae aliquam diam molestie eget. In et finibus ante, a mattis risus. In ullamcorper libero id enim aliquet, id posuere sem consectetur. Donec mi arcu, ultricies nec odio id, vestibulum luctus elit. Aliquam erat volutpat. Pellentesque sed sapien nulla. Pellentesque vitae pulvinar magna, quis ullamcorper leo. Aenean vehicula pretium nisi, at mattis orci aliquet eu.'
    ];
    return view('home', ['articles' => $articles]);
});
Route::get('/welcome', function () {
    return view('welcome');
});

Route::resource('articles', ArticleController::class);
